"""Add subject field in template model

Revision ID: f5e8340bdcc4
Revises: b6af1ab4326c
Create Date: 2025-07-02 21:01:39.522610

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5e8340bdcc4"
down_revision: Union[str, None] = "b6af1ab4326c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("subject", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "subject")
    # ### end Alembic commands ###
