.PHONY: run
run:
	@docker compose -f docker-compose.gorbunov.yml build && docker compose -f docker-compose.gorbunov.yml up

.PHONY: auth
auth:
	@docker compose -f docker-compose.auth_sprint.yaml build && docker compose -f docker-compose.auth_sprint.yaml up
