services:
  booking_service:
    build: .
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - logs:/app/logs
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:14
    container_name: booking_postgres
    restart: always
    volumes:
      - pg_auth:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

volumes:
  pg_auth:
  logs:
