"""init

Revision ID: 606951bf8101
Revises: 
Create Date: 2025-06-28 16:30:33.255688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606951bf8101'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.Column('sent_to', sa.UUID(), nullable=False),
    sa.Column('sent_address', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', 'error', 'sent', name='message_status_enum'), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
