version: "3.9"

services:
  tests:
    build:
      context: ./auth
      dockerfile: Dockerfile.tests
    container_name: tests_service
    volumes:
      - ./tests:/code/tests
    env_file:
      - auth/.env.test
    networks:
      - tests_network

  redis:
    image: redis:6.2
    container_name: redis_tests
    env_file:
      - auth/.env.test
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - tests_network

  test_postgres:
    image: postgres:14
    container_name: postgres_test
    restart: always
    volumes:
      - pg_auth:/var/lib/postgresql/data/
    env_file:
      - auth/.env.test
    ports:
      - 5432:5432
    networks:
      - tests_network

networks:
  tests_network:
    driver: bridge

volumes:
  pg_auth: