services:
  auth_service:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - main_network
    entrypoint: ["/app/entrypoint.sh"]
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - pg_auth:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - main_network

  redis:
    image: redis:6.2
    restart: unless-stopped
    env_file:
      - ./.env
    container_name: redis
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  pg_auth:
