"""Add partition table

Revision ID: 92d67c288b2a
Revises: 036d93d8f77d
Create Date: 2025-03-18 15:01:06.850300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92d67c288b2a"
down_revision: Union[str, None] = "036d93d8f77d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("device_type", sa.String(length=55), nullable=False, server_default="other"))
    op.create_index("idx_session_refresh_token", "sessions", ["refresh_token"], unique=False)
    op.create_unique_constraint("sessions_id_device_type_key", "sessions", ["id", "device_type"])
    op.alter_column("sessions", "device_type", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sessions_id_device_type_key", "sessions", type_="unique")
    op.drop_index("idx_session_refresh_token", table_name="sessions")
    op.drop_column("sessions", "device_type")
    # ### end Alembic commands ###
