"""Add location in address model

Revision ID: 1829fae950e0
Revises: bac394f13bd4
Create Date: 2025-08-10 19:02:30.426608

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1829fae950e0'
down_revision: Union[str, Sequence[str], None] = 'bac394f13bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.add_column('addresses', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.execute("UPDATE addresses SET location = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_addresses_location ON addresses USING GIST (location);")
    op.create_index('idx_user_id', 'addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='addresses')
    op.execute("DROP INDEX IF EXISTS idx_addresses_location;")
    op.drop_column('addresses', 'location')
    op.execute("DROP EXTENSION IF EXISTS postgis;")
    # ### end Alembic commands ###
